# https://travis-ci.org/#!/phlax/redis-docker

install:
  - make image

  # get redis cli
  - sudo apt-get install -y -qq --no-install-recommends redis-tools

script:

  # set the environment
  - echo "COMPOSE_FILE=./example/docker-compose.yml" > ./.env

  # up the redis server...
  - docker-compose up -d redis

  # check the server
  - docker-compose ps
  - docker-compose logs redis

  - ls ./redis
  - redis-cli -s ./redis/redis.sock ping
  - redis-cli -s ./redis/redis.sock set foo 100
  - redis-cli -s ./redis/redis.sock incr foo

  - docker-compose stop redis
  - docker-compose logs redis

before_deploy:
  - echo $DOCKER_PASSWORD | docker login -u phlax --password-stdin

deploy:
  provider: script
  script: make docker-push
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master)$
